branches:
  only:
    - master
language: node_js
node_js:
  - '14.7'
os: 
  linux 
arch:
  arm64 
before_install:
  - sudo apt-get update
  - npm install -g npm@latest
  - npm install -g typescript
  - sudo apt-get install xvfb
  - sudo apt-get install curl
  - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - apt-add-repository https://packages.microsoft.com/ubuntu/16.04/prod
  - sudo apt-get update
  - sudo apt-get install dotnet-runtime-3.1
  # - npm install -g @vue/cli
  # - sudo apt-get install chromium-browser
services: xvfb

install:
  - cd bot
  - npm i
  - npm i --only=dev
  - tsc
  - cd ..
  # - cd backend
  # - npm i 
  # - npm i --only=dev
  # - tsc
  # - cd ..
  # - cd frontend
  # - npm i 
  # - cd ..
  
script: 
  - npm run test --prefix bot
  # - npm run build --prefix frontend
  