branches:
  only:
    - master
language: node_js
node_js:
  - '14'

before_install:
  - sudo apt-get update -q
  - apt-transport-https dotnet-sdk-3.1 
install:
  - cd bot
  - npm i
  - npm i --only=dev
  - cd ..
  - cd backend
  - npm i 
  - npm i --only=dev
  - cd ..
  - cd frontend
  - npm i 
  
script: 
  - cd bot
  - tsc
  - npm run test
  - cd ..
  - cd backend
  - tsc
  - cd ..
  - cd frontend
  - npm run build   
  