branches:
  only:
    - master
language: node_js
node_js:
  - '14'
os: 
  linux 
arch:
  arm64 
dotnet: 3.1.0
before_install:
  - sudo apt-get update
  - sudo npm install -g typescript

install:
  - cd bot
  - npm i
  - npm i --only=dev
  - cd ..
  - cd backend
  - npm i 
  - npm i --only=dev
  - cd ..
  - cd frontend
  - npm i 
  - cd ..
  
script: 
  - cd bot
  - tsc
  - npm run test
  - cd ..
  - cd backend
  - tsc
  - cd ..
  - cd frontend
  - npm run build   
  