branches:
  only:
    - master
language: node_js
node_js:
  - '14.7'
os: 
  linux 
arch:
  arm64 
before_install:
  - sudo apt-get update
  - npm install -g npm@latest
  - npm install -g typescript
  - sudo apt-get install xvfb
  - sudo apt-get install wget
  - wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-runtime-3.1
  # - npm install -g @vue/cli
  # - sudo apt-get install chromium-browser
services: xvfb

install:
  - cd bot
  - npm i
  - npm i --only=dev
  - tsc
  - cd ..
  # - cd backend
  # - npm i 
  # - npm i --only=dev
  # - tsc
  # - cd ..
  # - cd frontend
  # - npm i 
  # - cd ..
  
script: 
  - npm run test --prefix bot
  # - npm run build --prefix frontend
  