branches:
  only:
    - master
language: csharp
os: 
  linux 
arch:
  arm64 
before_install:
  - sudo apt-get update
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - nvm install 14.7
  - nvm use 14.7
  - npm install -g npm@latest
  - npm install -g typescript
  - sudo apt-get install xvfb
  - sudo systemctl start xvfb
  - sudo apt-get install curl
  - sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add - 
  - sudo apt-add-repository https://packages.microsoft.com/ubuntu/16.04/prod
  - sudo apt-get update
  - sudo apt-get install dotnet-runtime-3.1
  # - npm install -g @vue/cli
  # - sudo apt-get install chromium-browser

install:
  - cd bot
  - npm i
  - npm i --only=dev
  - tsc
  - cd ..
  # - cd backend
  # - npm i 
  # - npm i --only=dev
  # - tsc
  # - cd ..
  # - cd frontend
  # - npm i 
  # - cd ..
  
script: 
  - npm run test --prefix bot
  # - npm run build --prefix frontend
  