branches:
  only:
    - master
language: node_js
node_js:
  - '14.7'
os: 
  linux 
arch:
  arm64 
dotnet: 3.1.0
services: xvfb
before_install:
  - sudo apt-get update
  - npm install -g typescript
  - npm install -g @vue/cli

install:
  - cd bot
  - npm i
  - npm i --only=dev
  - tsc
  - cd ..
  - cd backend
  - npm i 
  - npm i --only=dev
  - tsc
  - cd ..
  - cd frontend
  - npm i 
  - cd ..
  
script: 
  - npm run test --prefix bot
  - npm run build --prefix frontend
  