branches:
  only:
    - master
os: 
  linux 
arch:
  arm64 
dist: 
  bionic
before_install:
  - sudo apt-get update
  - nvm install 14.7
  - nvm use 14.7
  - npm install -g npm@latest
  - npm install -g typescript
  - sudo add-apt-repository ppa:tacorwin/dotnet 
  # - npm install -g @vue/cli
  # - sudo apt-get install chromium-browser
install:
  - cd bot
  - npm i
  - npm i --only=dev
  - tsc
  - cd ..
  # - cd backend
  # - npm i 
  # - npm i --only=dev
  # - tsc
  # - cd ..
  # - cd frontend
  # - npm i 
  # - cd ..
script: 
  - npm run test --prefix bot
  # - npm run build --prefix frontend
  